# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import time

# Data about this site
BLOG_AUTHOR = "Sun Xu"
BLOG_TITLE = "Blog"
SITE_URL = "http://sunxu.me"
BASE_URL = "/"
BLOG_EMAIL = "sunxu.name@gmail.com"
BLOG_DESCRIPTION = "keep curiosity."

# Nikola is multilingual!
DEFAULT_LANG = "en"
TRANSLATIONS = {
    DEFAULT_LANG: "",
}

# What will translated input files be named like?
TRANSLATIONS_PATTERN = "{path}.{lang}.{ext}"

# Links for the sidebar / navigation bar.
# You should provide a key-value pair for each used language.
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ('/index.html', 'Home', 'icon-home'),
        ('/archive', 'Archives', 'icon-folder-open-alt'),
        ('/tags', 'Tags', 'icon-tags'),
        ('/rss.xml', 'RSS', 'icon-rss'),
        ('/stories/about', 'About me', 'icon-user'),
        ('https://github.com/sunxu', 'My Github', 'icon-github'),
    ),
}

# Below this point, everything is optional

# While nikola can select a sensible locale for each language,
LOCALES = {'en':'zh_CN.UTF-8'} 
LOCALE_FALLBACK = 'zh_CN.UTF-8'
LOCALE_DEFAULT = 'zh_CN.UTF-8'

# POSTS and PAGES contains (wildcard, destination, template) tuples.
# POSTS are added to feeds, while PAGES are just independent HTML pages.
POSTS = (
("posts/*.md", "posts", "post.tmpl"),
("posts/*.slide", "posts", "remark.tmpl"),
("posts/*.html", "posts", "post.tmpl"),
)
PAGES = (
("stories/*.md", "stories", "story.tmpl"),
("stories/*.html", "stories", "story.tmpl"),
)

# One or more folders containing files to be copied as-is into the output.
# The format is a dictionary of "source" "relative destination".
FILES_FOLDERS = {'files': '' }

# A mapping of languages to file-extensions that represent that language.
COMPILERS = {
"markdown": ('.md', '.mdown', '.markdown'),
"remark": ('.slide',),
"html": ('.html', '.htm'),
}

# Create by default posts in one file format?
ONE_FILE_POSTS = True

# Paths for different autogenerated bits. These are combined with the
# translation paths.
TAG_PATH = "tags"

# If TAG_PAGES_ARE_INDEXES is set to True, each tag's page will contain
# the posts themselves. If set to False, it will be just a list of links.
TAG_PAGES_ARE_INDEXES = False 

# Final location for the main blog page and sibling paginated pages 
INDEX_PATH = ""

# Create per-month archives instead of per-year
CREATE_MONTHLY_ARCHIVE = True

# Create one large archive instead of per-year
CREATE_SINGLE_ARCHIVE = False

# Final locations for the archives 
ARCHIVE_PATH = "archive"
ARCHIVE_FILENAME = "index.html"

# URLs to other posts/pages can take 3 forms:
# rel_path: a relative URL to the current page/post (default)
# full_path: a URL with the full path from the root
# absolute: a complete URL (that includes the SITE_URL)
URL_TYPE = 'rel_path'

# Final location for the blog main RSS feed 
RSS_PATH = ""

# Number of posts in RSS feeds
FEED_LENGTH = 10

# Slug the Tag URL easier for users to type, special characters are
# often removed or replaced as well.
SLUG_TAG_PATH = True

# A list of redirection tuples, [("foo/from.html", "/bar/to.html")].
REDIRECTIONS = []

# Commands to execute to deploy. Can be anything
DEPLOY_COMMANDS = [
    "rsync -rav --delete output/ /var/sunxu.me"
]

# Where the output site should be located
OUTPUT_FOLDER = 'output'

# where the "cache" of partial generated content should be located
CACHE_FOLDER = 'cache'

# Filters to apply to the output.
FILTERS = {
    #".jpg": ["jpegoptim --strip-all -m75 -v %s"],
}

# Compiler to process LESS files.
LESS_COMPILER = 'lessc'

# A list of options to pass to the LESS compiler.
# Final command is: LESS_COMPILER LESS_OPTIONS file.less
LESS_OPTIONS = ["--modify-var=FontAwesomePath='../fonts'"]

# #############################################################################
# Image Gallery Options
# #############################################################################

# Galleries are folders in galleries/
# Final location of galleries will be output / GALLERY_PATH / gallery_name
# GALLERY_PATH = "galleries"
# THUMBNAIL_SIZE = 180
# MAX_IMAGE_SIZE = 1280
# USE_FILENAME_AS_TITLE = True
# EXTRA_IMAGE_EXTENSIONS = []
#
# If set to False, it will sort by filename instead. Defaults to True
# GALLERY_SORT_BY_DATE = True

# #############################################################################
# HTML fragments and diverse things that are used by the templates
# #############################################################################

# Data about post-per-page indexes.
# INDEXES_PAGES defaults to 'old posts, page %d' or 'page %d' (translated),
# depending on the value of INDEXES_PAGES_MAIN.
# INDEXES_TITLE = ""         # If this is empty, defaults to BLOG_TITLE
# INDEXES_PAGES = ""         # If this is empty, defaults to '[old posts,] page %d' (see above)
# INDEXES_PAGES_MAIN = False # If True, INDEXES_PAGES is also displayed on
                             # the main (the newest) index page (index.html)

# Name of the theme to use.
THEME = "zen"

# date format used to display post dates.
DATE_FORMAT = '%Y-%m-%d %H:%M'

# FAVICONS contains (name, file, size) tuples.
FAVICONS = {}

# Show only teasers in the index pages? Defaults to False.
INDEX_TEASERS = True

# A HTML fragment with the Read more... link.
READ_MORE_LINK = '<p class="more"><a href="{link}">{read_more}…</a></p>'

# A HTML fragment describing the license, for the sidebar.
# http://creativecommons.org/choose/
LICENSE = ""

# A small copyright notice for the page footer (in HTML).
CONTENT_FOOTER = '''Contents &copy; {date} {author}
{license}'''
CONTENT_FOOTER = CONTENT_FOOTER.format(email=BLOG_EMAIL,
                                       author=BLOG_AUTHOR,
                                       date=time.gmtime().tm_year,
                                       license=LICENSE)

# To use comments
COMMENT_SYSTEM = ""
COMMENT_SYSTEM_ID = ""

# Enable annotations using annotateit.org?
ANNOTATIONS = False

# Create index.html for story folders?
STORY_INDEX = True
# Enable comments on story pages?
COMMENTS_IN_STORIES = False
# Enable comments on picture gallery pages?
COMMENTS_IN_GALLERIES = False

# What file should be used for directory indexes?
INDEX_FILE = "index.html"

# If a link ends in /index.html,  drop the index.html part.
STRIP_INDEXES = True 

# Should the sitemap list directories which only include other directories
# and no files.
SITEMAP_INCLUDE_FILELESS_DIRS = False

# Instead of putting files in <slug>.html, put them in
# <slug>/index.html. Also enables STRIP_INDEXES
PRETTY_URLS = True 

# If True, publish future dated posts right away instead of scheduling them.
FUTURE_IS_NOW = True

# If True, future dated posts are allowed in deployed output
DEPLOY_FUTURE = True 
# If False, draft posts will not be deployed
DEPLOY_DRAFTS = False

# Do you want a add a Mathjax config file?
MATHJAX_CONFIG = ""

# What MarkDown extensions to enable?
# You will also get gist, nikola and podcast because those are
# done in the code, hope you don't mind ;-)
# MARKDOWN_EXTENSIONS = ['fenced_code', 'codehilite']

# Social buttons
SOCIAL_BUTTONS_CODE = ""

# Hide link to source for the posts?
HIDE_SOURCELINK = True 
# Copy the source files for your pages?
COPY_SOURCES = False

# Modify the number of Post per Index Page
INDEX_DISPLAY_POST_COUNT = 10

# Show only teasers in the RSS feed? Default to True
RSS_TEASERS = True

# A search form to search this site, for the sidebar. You can use a google
# custom search (http://www.google.com/cse/)
SEARCH_FORM = ""
#<form id="search" action="http://google.com/search" method="get" class="navbar-form pull-left">
#<input type="hidden" name="q" value="site:%s" />
#<input type="text" name="q" maxlength="255" results="0" placeholder="Search"/>
#</form>

# Use content distribution networks for jquery and twitter-bootstrap css and js
USE_CDN = False

# Extra things you want in the pages HEAD tag. This will be added right
# before </head>
EXTRA_HEAD_DATA = ""
# Google Analytics or whatever else you use. Added to the bottom of <body>
# in the default template (base.tmpl).
BODY_END = ""

# Additional metadata that is added to a post when creating a new_post
ADDITIONAL_METADATA = {}

# Post's dates are considered in UTC by default
TIMEZONE = 'Asia/Shanghai'

# If webassets is installed, bundle JS and CSS to make site loading faster
USE_BUNDLES = True

# Plugins you don't want to use. Be careful :-)
DISABLED_PLUGINS = []

# Add the absolute paths to directories containing plugins to use them.
EXTRA_PLUGINS_DIRS = ['plugins']

# Experimental plugins - use at your own risk.
ENABLED_EXTRAS = []

# List of regular expressions, links matching them will always be considered
# valid by "nikola check -l"
LINK_CHECK_WHITELIST = []

# If set to True, enable optional hyphenation in your posts (requires pyphen)
HYPHENATE = False

# You can configure the logging handlers installed as plugins or change the
# log level of the default stdout handler.
LOGGING_HANDLERS = {
    'stderr': {'loglevel': 'WARNING', 'bubble': True},
}

# Templates will use those filters, along with the defaults.
# Consult your engine's documentation on filters if you need help defining
# those.
TEMPLATE_FILTERS = {}

# Put in global_context things you want available on all your templates.
# It can be anything, data, functions, modules, etc.
GLOBAL_CONTEXT = {}
